;*******************************************************************************
;                                                                              *
;       CCD_calib.pro                                                          *
;                                                                              *
;       Carl W. Akerlof                                                        *
;       Randall Laboratory of Physics                                          *
;       500 East University                                                    *
;       University of Michigan                                                 *
;       Ann Arbor, Michigan  48109                                             *
;                                                                              *
;                                                                              *
;       November 16, 2002                                                      *
;                                                                              *
;*******************************************************************************

FUNCTION ccd_calib, DATE_STRING
IQD=GAUSS_CVF(0.25D0)-GAUSS_CVF(0.75D0)
T_BEGIN=SYSTIME(1)
BW_FLAG=1B*0B
DATA_FILES=DATE_STRING+'*_med.fit'
REPEAT BEGIN
   MED_FILES=FINDFILE(DATA_FILES, COUNT=N_FILES)
ENDREP UNTIL (N_FILES GT 0)
MED_FILES=MED_FILES[SORT(MED_FILES)]
RMS_FILES=STRARR(N_FILES)
T_VAL=DBLARR(N_FILES)
NT_VAL=N_FILES
FOR I = 0, N_FILES-1 DO BEGIN
   NS=RSTRPOS(MED_FILES[I], '_med.fit')
   RMS_FILES[I]=STRMID(MED_FILES[I], 0, NS)+'_rms.fit'
   NS=RSTRPOS(MED_FILES[I], DATE_STRING)
   S=STRMID(MED_FILES[I], NS)
   NS=STRPOS(S, '_')+4
   T_VAL[I]=DOUBLE(STRMID(S, NS, 4))/10.0D0
ENDFOR
NS=RSTRPOS(S, '_med')
S=STRMID(S, 0, NS)
NS=RSTRPOS(S, '_')
FILE_SUFFIX=STRMID(S, NS)
SEQ_NAME=DATE_STRING+FILE_SUFFIX
OUT_FILE='CCD_calib_'+DATE_STRING+FILE_SUFFIX
PLOT_A=OUT_FILE+'_a.ps'
PLOT_B=OUT_FILE+'_b.ps'
BADPIX_FILE=OUT_FILE+'_c.fits'
GET_LUN, UNIT
OPENW, UNIT, OUT_FILE+'_d.txt'
PRINTF, UNIT, 'File sequence: ', SEQ_NAME
PRINTF, UNIT, ''
PRINT, 'begin calculation: ', SYSTIME(0)
PRINTF, UNIT, 'begin calculation: ', SYSTIME(0)
DNX=2048L
NXA=53L
NXB=NXA+DNX
DNY=2048L
NYA=2L
NYB=NYA+DNY
N_PIX=DNX*DNY
MED0=READFITS(MED_FILES[0], /SILENT)
MED0=DOUBLE(REFORM(MED0[NXA:NXB-1,NYA:NYB-1], N_PIX))
BADPIX=BYTARR(N_PIX)
;
;       Estimate b, d parameters
;
M_A=DOUBLE(NT_VAL)
M_B=TOTAL(T_VAL, /DOUBLE)
M_C=TOTAL(T_VAL^2, /DOUBLE)
M_INV=[[M_C,-M_B],[-M_B,M_A]]/(M_A*M_C-M_B^2)
N_SAMP=LONARR(NT_VAL)
UA=DBLARR(N_PIX)
UB=DBLARR(N_PIX)
FOR I = 0, NT_VAL-1 DO BEGIN
   MED=READFITS(MED_FILES[I], HDR, /SILENT)
   MED=REFORM(MED[NXA:NXB-1,NYA:NYB-1], N_PIX)-MED0
   UA=UA+MED
   UB=UB+T_VAL[I]*MED
   N_SAMP[I]=SXPAR(HDR, 'NMED')
ENDFOR
BD=M_INV##[[UA],[UB]]
MED=0B
UA=0B
UB=0B
MSKTOT=0B
FOR I = 0, NT_VAL-1 DO MSKTOT=MSKTOT OR 2B^(I+2)
I=N_PIX/4L
B=REFORM(BD[*,0])
B=TEMPORARY(B[SORT(B)])
B_AV=0.5D0*(B[2L*I-1]+B[2L*I])
B_IQD=0.5D0*(B[3*I-1]+B[3*I]-B[I-1]-B[I])
B_MIN=B_AV-4.5D0*B_IQD/IQD
B_MAX=B_AV+4.5D0*B_IQD/IQD
INDX=WHERE((BD[*,0] LT B_MIN) OR (BD[*,0] GT B_MAX), N_INDX)
IF (N_INDX GT 0) THEN BADPIX[INDX]=MSKTOT
D=REFORM(BD[*,1])
D=TEMPORARY(D[SORT(D)])
D_AV=0.5D0*(D[2L*I-1]+D[2L*I])
D_IQD=0.5D0*(D[3*I-1]+D[3*I]-D[I-1]-D[I])
D_MIN=D_AV-4.5D0*D_IQD/IQD
D_MAX=D_AV+4.5D0*D_IQD/IQD
INDX=WHERE((BD[*,1] LT D_MIN) OR (BD[*,1] GT D_MAX), N_INDX)
IF (N_INDX GT 0) THEN BADPIX[INDX]=MSKTOT
DT_AV=D_AV*T_VAL[NT_VAL-1]
B=0B
D=0B
;
;       Estimate r, c, f parameters
;
M=DBLARR(3, 3)
M[0,0]=DOUBLE(N_PIX*NT_VAL)
QV=DBLARR(3)
FOR I = 0, NT_VAL-1 DO BEGIN
   VAR=READFITS(RMS_FILES[I], /SILENT)
   VAR=DOUBLE(REFORM(VAR[NXA:NXB-1,NYA:NYB-1], N_PIX))^2
   VAR_MED=MEDIAN(VAR)
   INDX=WHERE(ABS(VAR/VAR_MED-1.0D0) GT 4.5D0, N_INDX)
   MASK=2B^(I+2)
   IF (N_INDX GT 0) THEN BADPIX[INDX]=BADPIX[INDX] OR MASK
   D_T=REFORM(BD[*,1]*T_VAL[I])
   INDX=WHERE(BADPIX NE 0B, N_INDX)
   IF (N_INDX GT 0) THEN BEGIN
      D_T[INDX]=0.0D0
      VAR[INDX]=0.0D0
   ENDIF
   M[1,0]=M[1,0]+TOTAL(D_T, /DOUBLE)
   M[2,0]=M[2,0]+TOTAL(D_T^2, /DOUBLE)
   M[2,1]=M[2,1]+TOTAL(D_T^3, /DOUBLE)
   M[2,2]=M[2,2]+TOTAL(D_T^4, /DOUBLE)
   QV[0]=QV[0]+TOTAL(VAR, /DOUBLE)
   QV[1]=QV[1]+TOTAL(VAR*D_T, /DOUBLE)
   QV[2]=QV[2]+TOTAL(VAR*D_T^2, /DOUBLE)
ENDFOR
M[1,1]=M[2,0]
CHOLDC, M, P, /DOUBLE
QW=CHOLSOL(M, P, QV, /DOUBLE)
VAR=0B
D_T=0B
PARAMS=[SQRT(QW[0]),1.0D0/QW[1],(QW[2]/QW[1])*DT_AV]
PRINTF, UNIT, 'r, c, f initial:', PARAMS, FORMAT='(A,3F10.6)'
PRINT, 'r, c, f initial:', PARAMS, FORMAT='(A,3F10.6)'
BADPIX1=WHERE(BADPIX GT 0B, N_BADPIX1)
BADPIX2=WHERE(BADPIX GT 0B, N_BADPIX2)
PIX_CUT1=(GAUSS_CVF(1.0D0/DOUBLE(N_PIX*NT_VAL)))^2
PIX_CUT2=CHISQR_CVF(1.0D0/DOUBLE(N_PIX), NT_VAL-2)
ERR_CUR=0B
ITER_CNT=0L
REPEAT BEGIN
;
;       Estimate intermediate time values
;
FOR I = 1, NT_VAL-2 DO BEGIN
   W=BD[*,1]*T_VAL[I]
   W=!DPI*(QW[0]+QW[1]*W+QW[2]*W^2)/DOUBLE(2L*N_SAMP[I])+1.0D0/12.0D0
   W=1.0D0/TEMPORARY(W)
   MED=READFITS(MED_FILES[I], /SILENT)
   MED=REFORM(MED[NXA:NXB-1,NYA:NYB-1], N_PIX)-MED0
   IF (N_BADPIX1 GT 0L) THEN W[BADPIX1]=0.0D0
   MD_SUM=TOTAL(W*MED*BD[*,1], /DOUBLE)
   BD_SUM=TOTAL(W*BD[*,0]*BD[*,1], /DOUBLE)
   DD_SUM=TOTAL(W*BD[*,1]^2, /DOUBLE)
   T_VAL[I]=(MD_SUM-BD_SUM)/DD_SUM
ENDFOR
ITER_CNT=ITER_CNT+1L
PRINTF, UNIT, ''
PRINT, ''
PRINTF, UNIT, ' iteration', ITER_CNT, FORMAT='(A,I3)'
PRINT, ' iteration', ITER_CNT, FORMAT='(A,I3)'
PRINTF, UNIT, ' exposure durations:', T_VAL, FORMAT='(A,8F10.4)'
PRINT, ' exposure durations:', T_VAL, FORMAT='(A,8F10.4)'
;
;       Re-calculate b, d using variance weighted sums
;
CHISQ=DBLARR(N_PIX)
M_A=DBLARR(N_PIX)
M_B=DBLARR(N_PIX)
M_C=DBLARR(N_PIX)
UA=DBLARR(N_PIX)
UB=DBLARR(N_PIX)
FOR I = 0, NT_VAL-1 DO BEGIN
   W=BD[*,1]*T_VAL[I]
   W=!DPI*(QW[0]+QW[1]*W+QW[2]*W^2)/DOUBLE(2L*N_SAMP[I])+1.0D0/12.0D0
   W=1.0D0/TEMPORARY(W)
   MED=READFITS(MED_FILES[I], /SILENT)
   MED=REFORM(MED[NXA:NXB-1,NYA:NYB-1], N_PIX)-MED0
   CHISQ=CHISQ+W*MED^2
   M_A=M_A+W
   UA=UA+W*MED
   W=W*T_VAL[I]
   M_B=M_B+W
   UB=UB+W*MED
   M_C=M_C+W*T_VAL[I]
ENDFOR
M_D=M_A*M_C-M_B^2
BD[*,0]=(+M_C*UA-M_B*UB)/M_D
BD[*,1]=(-M_B*UA+M_A*UB)/M_D
CHISQ=CHISQ+M_A*BD[*,0]^2+2.0D0*M_B*BD[*,0]*BD[*,1]+M_C*BD[*,1]^2              $
           -2.0D0*(UA*BD[*,0]+UB*BD[*,1])
BADPIX=BADPIX AND (MSKTOT OR 1B)
BADPIX2=WHERE(CHISQ GT PIX_CUT2, N_BADPIX2)
IF (N_BADPIX2 GT 0L) THEN BADPIX[BADPIX2]=BADPIX[BADPIX2] OR 2B
BADPIX2=WHERE((BADPIX AND (MSKTOT OR 2B)) GT 0B, N_BADPIX2)
CHISQ_AV=TOTAL(CHISQ, /DOUBLE)
IF (N_BADPIX1 GT 0L) THEN CHISQ_AV=CHISQ_AV-TOTAL(CHISQ[BADPIX1], /DOUBLE)
CHISQ_AV=CHISQ_AV/DOUBLE(N_PIX-N_BADPIX1)
MED=0B
M_A=0B
M_B=0B
M_C=0B
M_D=0B
UA=0B
UB=0B
W=0B
PRINTF, UNIT, ' {b}, {d} <chi square>:', CHISQ_AV, FORMAT='(A,F12.6)'
PRINT, ' {b}, {d} <chi square>:', CHISQ_AV, FORMAT='(A,F12.6)'
;
;       Re-calculate r, c, f using variance weighted sums
;
M=DBLARR(3, 3)
QV=DBLARR(3)
WQ=2.0D0*!DPI/(IQD*EXP(-0.5D0*(IQD/2.0D0)^2))^2
FOR I = 0, NT_VAL-1 DO BEGIN
   D_T=REFORM(BD[*,1]*T_VAL[I])
   W=QW[0]+QW[1]*D_T+QW[2]*D_T^2
   W=WQ*W^2/DOUBLE(N_SAMP[I])+4.0D0*W/(6.0D0*IQD^2)
   W=1.0D0/TEMPORARY(W)
   VAR=READFITS(RMS_FILES[I], /SILENT)
   VAR=DOUBLE(REFORM(VAR[NXA:NXB-1,NYA:NYB-1], N_PIX))^2
   IF (N_BADPIX2 GT 0L) THEN W[BADPIX2]=0.0D0
   M[0,0]=M[0,0]+TOTAL(W, /DOUBLE)
   QV[0]=QV[0]+TOTAL(W*VAR, /DOUBLE)
   W=W*D_T
   M[1,0]=M[1,0]+TOTAL(W, /DOUBLE)
   QV[1]=QV[1]+TOTAL(W*VAR, /DOUBLE)
   W=W*D_T
   M[2,0]=M[2,0]+TOTAL(W, /DOUBLE)
   QV[2]=QV[2]+TOTAL(W*VAR, /DOUBLE)
   W=W*D_T
   M[2,1]=M[2,1]+TOTAL(W, /DOUBLE)
   W=W*D_T
   M[2,2]=M[2,2]+TOTAL(W, /DOUBLE)
ENDFOR
M[1,1]=M[2,0]
P=DBLARR(3)
M_INV=DBLARR(3, 3)
CHOLDC, M, P, /DOUBLE
FOR I = 0, 2 DO BEGIN
   W=DOUBLE([0,0,0])
   W[I]=1.0D0
   M_INV[I,*]=CHOLSOL(M, P, W, /DOUBLE)
ENDFOR
QR=QW
QW=M_INV##QV
VAR=0B
D_T=0B
ERR_VAL=ABS(1.0D0-QW[0]/QR[0])+ABS(1.0D0-QW[1]/QR[1])
ERR_PRV=ERR_CUR
ERR_CUR=ERR_VAL LT 0.001D0
PARAMS=[SQRT(QW[0]),1.0D0/QW[1],(QW[2]/QW[1])*DT_AV]
R_ERR=0.5D0*SQRT(M_INV[0,0]/QW[0])
C_ERR=SQRT(M_INV[1,1])/QW[1]^2
F_ERR=SQRT(M_INV[1,1]*QW[2]^2-2.0D0*M_INV[1,2]*QW[1]*QW[2]+M_INV[2,2]*QW[1]^2)
DPARAMS=[R_ERR,C_ERR,DT_AV*F_ERR/QW[1]^2]
PRINTF, UNIT, ' r, c, f values:', PARAMS, FORMAT='(A,3F10.6)'
PRINT, ' r, c, f values:', PARAMS, FORMAT='(A,3F10.6)'
PRINTF, UNIT, ' r, c, f errors:', DPARAMS, FORMAT='(A,3F10.6)'
PRINT, ' r, c, f errors:', DPARAMS, FORMAT='(A,3F10.6)'
PRINTF, UNIT, ' iteration error:', ERR_VAL, ERR_PRV, ERR_CUR,                  $
        FORMAT='(A,F9.6,2I4)'
PRINT, ' iteration error:', ERR_VAL, ERR_PRV, ERR_CUR, FORMAT='(A,F9.6,2I4)'
;
;       Calculate Chi Square for each N_PIX*NT_VAL measurements of noise
;
BADPIX=BADPIX AND (MSKTOT OR 2B)
CHI_SUM=0.0D0
FOR I = 0, NT_VAL-1 DO BEGIN
   D_T=REFORM(BD[*,1]*T_VAL[I])
   W=QW[0]+QW[1]*D_T+QW[2]*D_T^2
   W=WQ*W^2/DOUBLE(N_SAMP[I])+4.0D0*W/(6.0D0*IQD^2)
   W=1.0D0/TEMPORARY(W)
   VAR=READFITS(RMS_FILES[I], /SILENT)
   VAR=DOUBLE(REFORM(VAR[NXA:NXB-1,NYA:NYB-1], N_PIX))^2
   U=W*(QW[0]+QW[1]*D_T+QW[2]*D_T^2-VAR)^2
   INDX=WHERE(U GT PIX_CUT1, N_INDX)
   IF (N_INDX GT 0L) THEN BADPIX[INDX]=BADPIX[INDX] OR 1B
   IF (N_BADPIX2 GT 0L) THEN U[BADPIX2]=0.0D0
   CHI_SUM=CHI_SUM+TOTAL(U, /DOUBLE)
ENDFOR
N_CHI=NT_VAL*(N_PIX-N_BADPIX2)
CHI_SUM=CHI_SUM/DOUBLE(N_CHI-3L)
BADPIX1=WHERE((BADPIX AND (MSKTOT OR 1B)) GT 0B, N_BADPIX1)
ENDREP UNTIL (ERR_PRV AND ERR_CUR)
;
;       Plot integral Chi Square distribution for N_PIX fits of b & d
;
IF (N_BADPIX1 GT 0L) THEN CHISQ[BADPIX1]=-1.0D0
INDX=SORT(CHISQ)
I_LIM=CEIL(0.95D0*DOUBLE(N_PIX-N_BADPIX1)+DOUBLE(N_BADPIX1)) < N_PIX-1L
X_MAX=CEIL(CHISQ[INDX[I_LIM]])
INDX=0B
X_BINS=1000L*X_MAX
X_CHISQ=DINDGEN(X_BINS+1L)/DOUBLE(1000L)
DY=HISTOGRAM(CHISQ < 1000.0D0, MIN=0.0D0, BINSIZE=0.001D0)
Y_CHISQ_E=LONARR(X_BINS+1L)
FOR I = 1L, X_BINS DO Y_CHISQ_E[I]=Y_CHISQ_E[I-1]+DY[I-1]
Y_CHISQ_E=DOUBLE(Y_CHISQ_E)/DOUBLE(N_PIX-N_BADPIX1)

y_chisq_c = dblarr(n_elements(x_chisq))
for i=0l,n_elements(x_chisq)-1 do begin
    y_chisq_c[i] = chisqr_pdf(x_chisq[i], nt_val-2l)
endfor

;;Y_CHISQ_C=CHISQR_PDF(X_CHISQ, NT_VAL-2L)
PIX_STR=STRTRIM(STRING(DNX), 2)+' !9X!5 '+STRTRIM(STRING(DNY), 2)+' pixels'
RED=[000B,255B,255B,000B,000B,255B,000B,255B,255B]
GRN=[000B,255B,000B,255B,000B,000B,255B,140B,255B]
BLU=[000B,255B,000B,000B,255B,255B,255B,020B,000B]
TVLCT, RED, GRN, BLU
DEV_NAME=!D.NAME
IF (BW_FLAG EQ 0) THEN BEGIN
   COLOR_FLAG=1B
   A_TITLE='!5'+SEQ_NAME+' b, d integral !7v!5!E2!N'
   B_TITLE='!5'+SEQ_NAME+' r, c, f integral !5(!7d!5/!7r!5)!E2!N'
   COLOR_2=2B
   LSTYLE=0B
ENDIF ELSE BEGIN
   COLOR_FLAG=0B
   A_TITLE=''
   B_TITLE=''
   COLOR_2=1B
   LSTYLE=2B
ENDELSE
FOR I_DEV = 0, 1 DO BEGIN
   IF (I_DEV EQ 0) THEN BEGIN
      DEVICE, DECOMPOSED=0
   ENDIF ELSE BEGIN
      SET_PLOT, 'PS'
      DEVICE, FILENAME=PLOT_A, COLOR=COLOR_FLAG
   ENDELSE
   PLOT, X_CHISQ, Y_CHISQ_E, XRANGE=[0.0D0,X_MAX], /XSTYLE, TITLE=A_TITLE,     $
         XTITLE='!7v!5!E2!N', YTITLE='!5F(!7v!5!E2!N)', XTICKLEN=0.03,         $
         XMINOR=5, CHARSIZE=1.4, CHARTHICK=2.0, XTHICK=4.0, YTHICK=4.0,        $
         THICK=4.0
   OPLOT, X_CHISQ, Y_CHISQ_C, COLOR=COLOR_2, THICK=4.0, LINESTYLE=LSTYLE
   STR='!5<!7v!5!E2!N> = '+STRTRIM(STRING(CHISQ_AV, FORMAT='(F10.3)'), 2)
   XS=0.90D0*DOUBLE(X_MAX)
   YS=0.12D0
   XYOUTS, XS, YS, STR, ALIGNMENT=1.0, CHARTHICK=2.0
   YS=YS-0.06D0
   XYOUTS, XS, YS, PIX_STR, ALIGNMENT=1.0, CHARTHICK=2.0
   IF (I_DEV EQ 1) THEN DEVICE, /CLOSE_FILE
ENDFOR
SET_PLOT, DEV_NAME
;
;       Compute Chi Square for r, c, f estimate
;
CHI_SUM=0.0D0
FOR I = 0, NT_VAL-1 DO BEGIN
   D_T=REFORM(BD[*,1]*T_VAL[I])
   W=QW[0]+QW[1]*D_T+QW[2]*D_T^2
   W=WQ*W^2/DOUBLE(N_SAMP[I])+4.0D0*W/(6.0D0*IQD^2)
   W=1.0D0/TEMPORARY(W)
   VAR=READFITS(RMS_FILES[I], /SILENT)
   VAR=REFORM(VAR[NXA:NXB-1,NYA:NYB-1], N_PIX)^2
   IF (N_BADPIX2 GT 0L) THEN W[BADPIX2]=0.0D0
   U=W*(QW[0]+QW[1]*D_T+QW[2]*D_T^2-VAR)^2
   CHI_SUM=CHI_SUM+TOTAL(U, /DOUBLE)
   DZ=HISTOGRAM(U < 1000.0D0, MIN=0.0D0, BINSIZE=0.001D0)
   NDZ=N_ELEMENTS(DZ)
   IF (I EQ 0) THEN BEGIN
      DY=DZ
      NDY=NDZ
   ENDIF ELSE BEGIN
      IF (NDY GE NDZ) THEN BEGIN
         DY[0L:NDZ-1L]=DY[0L:NDZ-1L]+DZ[0L:NDZ-1L]
      ENDIF ELSE BEGIN
         DZ[0L:NDY-1L]=DY[0L:NDY-1L]+DZ[0L:NDY-1L]
         DY=DZ
         NDY=NDZ
      ENDELSE
   ENDELSE
ENDFOR
N_CHI=NT_VAL*(N_PIX-N_BADPIX2)
CHISQ_AV=TOTAL(CHI_SUM)/DOUBLE(N_CHI-3L)
PRINTF, UNIT, ''
PRINT, ''
PRINTF, UNIT, 'r, c, f chi square:', CHISQ_AV, FORMAT='(A,F10.6)'
PRINT, 'r, c, f chi square:', CHISQ_AV, FORMAT='(A,F10.6)'
Y_CHISQ_E=LONARR(NDY+1L)
FOR I = 1L, NDY DO Y_CHISQ_E[I]=Y_CHISQ_E[I-1]+DY[I-1]
I_LIM=CEIL(0.95D0*DOUBLE(N_CHI)) < N_CHI-1L
INDX=WHERE(Y_CHISQ_E LE I_LIM, N_INDX)
X_MAX=CEIL(DOUBLE(N_INDX)/1000.0D0)
NX_MAX=(1000L*X_MAX) < NDY
X_CHISQ=DINDGEN(NX_MAX+1L)/1000.0D0
Y_CHISQ_E=DOUBLE(Y_CHISQ_E[0:NX_MAX])/DOUBLE(N_CHI)
Y_CHISQ_C=2.0D0*GAUSS_PDF(SQRT(X_CHISQ))-1.0D0
DEV_NAME=!D.NAME
FOR I_DEV = 0, 1 DO BEGIN
   IF (I_DEV EQ 0) THEN BEGIN
      DEVICE, DECOMPOSED=0
   ENDIF ELSE BEGIN
      SET_PLOT, 'PS'
      DEVICE, FILENAME=PLOT_B, COLOR=COLOR_FLAG
   ENDELSE
   PLOT, X_CHISQ, Y_CHISQ_E, XRANGE=[0.0D0,X_MAX], /XSTYLE, TITLE=B_TITLE,     $
         XTITLE='!5(!7d!5!Di!N/!7r!5!Di!N)!E2!N',                              $
         YTITLE='!5F(!7d!5/!7r!5!N)', XTICKLEN=0.03, XMINOR=5,                 $
         CHARSIZE=1.4, CHARTHICK=2.0, XTHICK=4.0, YTHICK=4.0, THICK=4.0
   OPLOT, X_CHISQ, Y_CHISQ_C, COLOR=COLOR_2, THICK=4.0, LINESTYLE=LSTYLE
   STR='!7v!5!E2!N/dof = '+STRTRIM(STRING(CHISQ_AV, FORMAT='(F10.3)'), 2)
   XS=0.90D0*DOUBLE(X_MAX)
   YS=0.12D0
   XYOUTS, XS, YS, STR, ALIGNMENT=1.0, CHARTHICK=2.0
   YS=YS-0.06D0
   XYOUTS, XS, YS, PIX_STR, ALIGNMENT=1.0, CHARTHICK=2.0
   IF (I_DEV EQ 1) THEN DEVICE, /CLOSE_FILE
ENDFOR
SET_PLOT, DEV_NAME
BADCNT=LONARR(NT_VAL+2)
FOR I = 0, NT_VAL+1 DO BEGIN
   MASK=2B^I
   BADCNT[I]=LONG(TOTAL((BADPIX AND MASK) GT 0B, /DOUBLE))
ENDFOR
PRINTF, UNIT, 'bad pixel counts:', N_BADPIX1, N_BADPIX2, FORMAT='(A,2I8)'
PRINT, 'bad pixel counts:', N_BADPIX1, N_BADPIX2, FORMAT='(A,2I8)'
PRINTF, UNIT, BADCNT, FORMAT='(17X,8I8)'
PRINT, BADCNT, FORMAT='(17X,8I8)'
BADPIX=REFORM(BADPIX, DNX, DNY)
WRITEFITS, BADPIX_FILE, BADPIX
XS=(DNX+2L)/3L
YS=(DNY+2L)/3L
WINDOW, XSIZE=XS, YSIZE=YS
INDX=WHERE(BADPIX NE 0, N_INDX)
X_INDX=(INDX MOD DNX)/3L
Y_INDX=(INDX/DNX)/3L
DISP=BYTARR(XS, YS)
DISP[X_INDX,Y_INDX]=255B
TV, DISP
T_END=SYSTIME(1)
S='end calculation: '+SYSTIME(0)
PRINTF, UNIT, S, (T_END-T_BEGIN)/60.0D0, ' minutes', FORMAT='(A,F9.3,A)'
PRINT, S, (T_END-T_BEGIN)/60.0D0, ' minutes', FORMAT='(A,F9.3,A)'
CLOSE, UNIT
FREE_LUN, UNIT
RETURN, [[PARAMS],[DPARAMS]]
END
