sobjlist sobjlist
workdir /rotse/data/pipeline
sobjdir /rotse/data/pipeline/prod
cobjdir /rotse/data/pipeline/prod
imgdir  /rotse/data/pipeline/image
statdir /rotse/data/pipeline/prod
statroot rotse3a
thumbfile /rotse/data/pipeline/thumbcopy
bindir /rotse/data/pipeline/prod
stampfile /rotse/data/pipeline/idlstamp
templatedir /rotse/data/pipeline/templates
linkdir null
