
pro rdis, image, pls,xmn=xmn, xmx=xmx, ymn=ymn, ymx=ymx, low=low, $
	high=high, log=log, zoom=zoom, full=full, flipx=flipx, flipy=flipy, $
	rot=rot, silent=silent, _extra=e

;+
; NAME:
;       RDIS
; PURPOSE:
;	Simple wrapper for tvim2
;
; CALLING SEQUENCE:
;       rdis, image, pls, xmn=xmin, xmx=xmax, ymn=ymin, ymx=ymax, 
;		low=low, high=high, log=log, zoom=zoom, full=full
;		flipx=flipx, flipy=flipy
;
; INPUTS:
;       image to be displayed
;	
;
; OPTIONAL OUTPUT ARRAYS:
;
; INPUT KEYWORD PARAMETERS:
;	pls = plot structure, generated by rdis_setup
;	  Must include:
;		xmn,xmx,ymn,ymx,low,high
;	limits
;	range values
;
; PROCEDURE:
;	the file 
;
; REVISION HISTORY:
;	Tim McKay	UM	1/29/97
;-
 On_error,2              ;Return to caller

 if N_params() eq 0 then begin
        print,'Syntax - rdis, image, pls, xmn=xmn, xmx=xmx, ymn=ymn, ymx=ymx,low=low, high=high, log=log, zoom=zoom, full=full, _extra=e'
        return
 endif

; First process the plot structure
  if (pls.xmn eq 0 and pls.xmx eq 0) then begin
	r=size(image)
	xmin=0
	xmax=r(1)-1
  endif else begin
	xmin=pls.xmn
	xmax=pls.xmx
  endelse
  
  if (pls.ymn eq 0 and pls.ymx eq 0) then begin
	r=size(image)
	ymin=0
	ymax=r(2)-1
  endif else begin
	ymin=pls.ymn
	ymax=pls.ymx
  endelse

  if keyword_set(log) then begin 
	imin=alog10(abs(image)) 
  endif else begin
	imin=image
  endelse
  
  if keyword_set(xmn) then begin
	xmin=xmn
  endif 

  if keyword_set(xmx) then begin
	xmax=xmx
  endif 

  if keyword_set(ymn) then begin
	ymin=ymn
  endif 

  if keyword_set(ymx) then begin
	ymax=ymx
  endif

  if keyword_set(silent) then silent=1 else silent=0
  if(pls.low eq pls.high) then begin

    sky,imin(xmin:xmax,ymin:ymax),mean,sigma,silent=silent
   
    if keyword_set(low) then begin
	rlow=low
    endif else begin
	rlow=mean-sigma
    endelse

    if keyword_set(high) then begin
	rhigh=high
    endif else begin
	rhigh=mean+5*sigma
    endelse

  endif else begin
    rlow=pls.low
    rhigh=pls.high
  endelse

  if keyword_set(zoom) then begin
 	m=1
	if zoom eq 1 then begin
;		rdis_setup, pls, im
		; Input keyword parameter
		cursor, x,y, /data, /up 
		cursor, x1, y1, /data, /up
            if (x1 le x) then begin
		xmin=x1
		xmax=x
 	        pls.xmn=x1
		pls.xmx=x  
	    endif else begin
		xmin=x
		xmax=x1
        	pls.xmn=x
		pls.xmx=x1    
	     endelse

	    if (y1 le y) then begin
		ymin=y1
  		ymax=y
        	pls.ymn=y1
		pls.ymx=y    
	    endif else begin
		ymin=y	    
		ymax=y1
 		pls.ymn=y
		pls.ymx=y1    
	    endelse

 	endif else begin      
		c1=(pls.xmx+pls.xmn)/2
		c2=(pls.ymx+pls.ymn)/2
		xmax=c1+(zoom*(pls.xmx-c1))	
		xmin=c1-(zoom*(c1-pls.xmn))	
		ymax=c2+(zoom*(pls.ymx-c2))	
		ymin=c2-(zoom*(c2-pls.ymn))	
	
	     if (xmin le 0) then begin
	    	xmin=0
 	     endif
             info=size(image)
	     if (xmax ge info(1)) then begin
	    	xmax=info(1)-1
 	     endif 
 	     if (ymin le 0) then begin
	    	ymin=0
 	     endif
	     if (ymax ge info(2)) then begin
	        ymax=info(2)-1
 	     endif 
 	     pls.xmn=xmin
	     pls.xmx=xmax
	     pls.ymn=ymin
	     pls.ymx=ymax  
 	endelse
 endif		

 if keyword_set(full) then begin
	rdis_setup, image, pls
	r=size(image)
	xmin=0
	xmax=r(1)-1
	ymin=0
	ymax=r(2)-1
 endif

 if keyword_set(flipx) then begin
      	if pls.xmn eq 0 then begin
	   imin=reverse(image)		
        endif else begin
	   r=size(image)
	   imin=reverse(image)
	   xmax=r(1)-pls.xmn
	   xmin=r(1)-pls.xmx 
        endelse
 endif

 if keyword_set(flipy) then begin
	if pls.ymn eq 0 then begin
	   imin=reverse(image, 2)		
        endif else begin
	   r=size(image)
	   imin=reverse(image,2)
	   ymax=r(2)-pls.ymn
	   ymin=r(2)-pls.ymx
        endelse
 endif

 if keyword_set(rot) then begin
	 if pls.ymn eq 0 then begin
           imin=rotate(image, 2)		
         endif else begin
	   r=size(image)
           imin=rotate(image,2)
	   xmax=r(1)-pls.xmn
	   xmin=r(1)-pls.xmx 
	   ymax=r(2)-pls.ymn
	   ymin=r(2)-pls.ymx
	 endelse
 endif

; Now do it
  if not keyword_set(silent) then begin
     print,"range=",rlow,rhigh
     print,"Displaying im(",xmin,":",xmax,",",ymin,":",ymax,")"
  endif
  tvim2_scl,imin,xmin,xmax,ymin,ymax,range=[rlow,rhigh],_extra=e

  return
  end



