pro examine_subs,str,im1,im2,imdiff,index=k,good_array=good_array
;+
; NAME:	EXAMINE_SUBS
;
; CALLING SEQUENCE: 
;
; INPUTS:	str: a structure generated by tycho_2sub
;		im1: image 1 from the sub
;		im2: image 2 from the sub
;		imdiff: the difference image
;
; OUTPUTS:	
;	
; INPUT KEYWORDS:
;	index: display only these objects
;			
; PROCEDURE:	
;
; REVISION HISTORY:  
;	Tim McKay		UM	12/15/98
;

;The idea is to loop over all the desired objects, displaying them simply...

 if N_params() eq 0 then begin
        print,'Syntax - examine_subs,str,im1,im2,imdiff,index=k'
	return
 endif

 gain=5.5
 ;Assume that the exposure used for subtraction is about 4 times as deep as
 ;this exposure (hence the factor of 1.25).....
 ratio=gain*str.fd/sqrt(1.5*gain*(str.f1+str.s1*3.1415*9.0))

 if not keyword_set(k) then begin
	k=where(ratio gt 10.0 and str.f2 lt 3000 and str.f1 ne 99.999 and $
		str.f2 ne 99.999 and str.fd ne 99.999)
 endif
 j=where(str.f1 ne 99.999 and str.f2 ne 99.999 and str.fd ne 99.999)

 n=n_elements(k)
 print,'Will examine a total of:'+string(n)

 
 !p.multi=[0,2,2]
 rdis_setup,im1,pls

 ngood=0
 for i=0, n-1 do begin
	o=k(i)
	print,'Object processed = ',o
	x=str.x(o)
	y=str.y(o)
	xl=x-40
	xh=x+40
	if (xl le 0) then xl=0
	if (xh ge 2034) then xh=2034
	yl=y-40
	yh=y+40
	if (yl le 0) then yl=0
	if (yh ge 2068) then yh=2068
	!p.title='Image 1'
	rdis,im1,pls,xmn=xl,xmx=xh,ymn=yl,ymx=yh
	tvcircle,5.0,[x],[y],/data,noclip=0
	!p.title='Image 2'
	rdis,im2*100.0,pls,xmn=xl,xmx=xh,ymn=yl,ymx=yh
	tvcircle,5.0,[x],[y],/data,noclip=0
	!p.title='Differenced image'
	rdis,imdiff,pls,xmn=xl,xmx=xh,ymn=yl,ymx=yh
	tvcircle,5.0,[x],[y],/data,noclip=0
	!p.title='S/N vs. f2'
	plot,ratio(j),str.f2(j),psym=3,yrange=[-100,7000],xrange=[0,20.0]
	if (str.f2(o) lt 7000 and ratio(o) lt 20.0) then begin
	    oplot,[ratio(o)],[str.f2(o)],psym=1
	endif else begin
	    arrow,ratio(o),6000.0,ratio(o),7000,/data
	endelse
	if (str.f2(o) lt 7000 and ratio(o) gt 20.0) then begin
	    arrow,15.0,str.f2(o),20.0,str.f2(o),/data
	endif
	result=get_kbrd(30)
	print,'You typed: ',result
	if (result eq 'y') then begin
	  if(ngood eq 0) then begin
		good=o
		ngood=ngood+1
	  endif else begin
		good=[good,o]
	  	ngood=ngood+1
	  endelse
	endif
	!p.title=''

end

print,'Number of selected objects is:',ngood
if (ngood gt 0) then good_array=good

!p.multi=[0,1,1]

return

end


