function focus_find_roots,focstr
;+
; NAME: focus_find_roots
;
; CALLING SEQUENCE: best = focus_find_roots(focstr)
;
; INPUTS:                  focstr: focus structure
; 
; RETURN VALUE:            best: array of best-focus structures
;
; PROCEDURE:  This program takes in a focstr as generated by gen_focus_fits,
;  and returns an array of best-focus structures.  This program is called by
;  gen_focus_model.pro
;
; REVISION HISTORY:
;    Eli Rykoff      UM    10/21/03 - First official version
;
;========================================================================
;-


if n_params() eq 0 then begin
    print,'syntax- focus_find_roots,focstr'
    return,-1
endif

elt=create_struct('file','', $
                  'best_focus', 0.0, $
                  'error', 0.0, $
                  'temp', 0.0, $
                  'elevation', 0.0, $
                  'azimuth', 0.0, $
                  'first', 0l, $
                  'last', 0l)

numsets = 0
for i=0l,n_elements(focstr)-1 do begin
    if (strpos(focstr[i].filename,'001_') ne -1) or $
      (strpos(focstr[i].filename,'001.') ne -1) then begin
        numsets = numsets+1
    endif
endfor

best=replicate(elt, numsets)
set = -1l
for i=0l,n_elements(focstr)-1 do begin
    if (strpos(focstr[i].filename,'001_') ne -1) or $
      (strpos(focstr[i].filename,'001.') ne -1) then begin
        if (set ne -1) then begin
            ;; we've finished the last set
            best[set].last = i-1
            best[set].temp = temptotal / float(numinset)
            best[set].azimuth = aztotal / float(numinset)
            best[set].elevation = elevtotal / float(numinset)
        endif
        ;; now initialize the new set
        set = set + 1
        best[set].first = i
        parts=str_sep(focstr[i].filename,'_')
        best[set].file=parts[0] + '_' + parts[1] + '_' + strmid(parts[2],0,2)
        print,best[set].file
        numinset = 0
        temptotal = 0.0
        elevtotal = 0.0
        aztotal = 0.0
    endif
    numinset = numinset + 1
    temptotal = temptotal + focstr[i].temp
    elevtotal = elevtotal + focstr[i].elevation
    aztotal = aztotal + focstr[i].azimuth
endfor
;; and set the last one
best[set].last = i-1
best[set].temp = temptotal / float(numinset)
best[set].azimuth = aztotal / float(numinset)
best[set].elevation = elevtotal / float(numinset)

return,best
end
