pro gen_focus_model,fitnames,best,mingd=mingd,useratio=useratio,fittconst=fittconst
;+
; NAME: gen_focus_model
;
; CALLING SEQUENCE: gen_focus_model,fitnames,best,mingd=mingd,useratio=useratio,fittconst=fittconst
;
; INPUTS:               fitnames:   array of focus fits files to use
;
; OUTPUTS:              best: an array of best-focus structures
;
; INPUT_KEYWORDS:       mingd: min. good points to do a fit
;                       useratio: use count ratio and not FWHM (requires proper sextraction)
;                       /fittconst: use an independent temp constant rather
;                        than calculated value of 0.00439
;
; PROCEDURE: This program reads in a single or array of focus information fits
;  files (generated by gen_focus_fits), and queries the user for each
;  individual focus run (using focus_find_best).  It then generates a best-fit
;  model with focus_find_fit.
;
; REVISION HISTORY:
;    Eli Rykoff    UM      10/21/03 - First official version
;
;==========================================================================
;-




if n_params() eq 0 then begin
    print,'syntax- gen_focus_model,fitnames,best,mingd=mingd,useratio=useratio,fittconst=fittconst'
    return
endif

if not keyword_set(fittconst) then tconst=0.00439

focstr = mrdfits(fitnames[0],1)
template = focstr[0]
if n_elements(fitnames) gt 1 then begin
    for i=1l,n_elements(fitnames)-1 do begin
        fs=mrdfits(fitnames[i],1)

        ftemplate = replicate(template,n_elements(fs))

        struct_assign,fs,ftemplate
        focstr=[focstr,ftemplate]
    endfor
endif

best = focus_find_roots(focstr)

focus_find_best,focstr,best,mingd=mingd,useratio=useratio


;focus_find_fit,best,result,tconst=tconst,etconst=etconst,e2tconst=e2tconst

focus_find_fit3,best,result,tconst=tconst


return
end
